### ISSUE TITLE
undefined symbol: _scm_object_hex_address

### ISSUE THREAD

**Issue by SaffronSnail** [artyom-poptsov/guile-ssh#1]
I'm on Arch Linux, I cloned your repository and built it, but when I ran "make check" five of the tests failed:

1. server.scm
2. session.scm
3. client-server.scm
4. server-client.scm
5. key.scm

In the log, all of the tests had the same symbol lookup error. The full log is attached.
[test-suite.txt](https://github.com/artyom-poptsov/guile-ssh/files/95381/test-suite.txt)

**Comment by artyom-poptsov** [comment]
Hello @SaffronSnail,

could you please run `make check -j1` on the latest 'master' and let me know if there are failing tests?

Also please include all `*.log` files from `tests` directory that are left after `make check -j1`.

Thanks!

-- Artyom

**Comment by SaffronSnail** [comment]
Hey, thanks for the response!

I did as you asked, and the tests were indeed still failing. All of the logs are attached.
[tests.zip](https://github.com/artyom-poptsov/guile-ssh/files/97088/tests.zip)

**Comment by artyom-poptsov** [comment]
Hello @SaffronSnail,

I checked Guile-SSH from the 'master' branch [on Arch GNU/Linux](https://hub.docker.com/r/marcelhuberfoo/arch/) and was able to reproduce the problem.  There were issues with inline procedures; 548b915 fixes them.  While I was on it I fixed some other issues as well.

It seems to me that Arch has libssh  0.7 in the repository, but I haven't tested Guile-SSH with that version.  The library is known to work with libssh 0.6.5, please check Guile-SSH 'master' with that version of libssh on Arch (I'll check if that works too as soon as I have time.)

Thanks for reporting,

-- Artyom

**Comment by artyom-poptsov** [comment]
Hi,

I checked Guile-SSH form the master branch with [libssh 0.6.5](https://red.libssh.org/attachments/download/121/libssh-0.6.5.tar.xz) on Arch GNU/Linux and `make check` finished successfully in 4 out of 4 runs:

``` bash
$ cd /home/avp/src/

# Get and build libssh sources
$ git clone git://git.libssh.org/projects/libssh.git
$ git checkout libssh-0.6.5
$ cd libssh/build
$ cmake ../

# Build Guile-SSH and run tests:
$ cd ~/src/guile-ssh
$ git checkout master
$ git pull
$ export LD_LIBRARY_PATH=/home/avp/src/libssh/build/src/
$ make clean && make
$ make check
```
Note that I exported `LD_LIBRARY_PATH` with the path to libssh 0.6.5 library so the subsequent `make` invocations used freshly compiled 0.6.5 version instead of 0.7.2-1 version installed by the system package manager.

Could you please check if it works for you?

-- Artyom

**Comment by SaffronSnail** [comment]
Hello again. Apologies that it took so long for me to get back to you. I can indeed confirm that it now passes the tests on my Arch system. Thanks for your assistance!

**Comment by artyom-poptsov** [comment]
You're welcome.

Also the latest Guile-SSH from the `master` branch now should work with libssh 0.7; please use at least libssh 0.7.3 because there's [a serious vulnerability](https://www.libssh.org/2016/02/23/libssh-0-7-3-security-and-bugfix-release/) in previous versions.

-- Artyom
