### ISSUE TITLE
Cross-compilation broken in 0.15.1

### ISSUE THREAD

**Issue by civodul** [artyom-poptsov/guile-ssh#30]
Hello!

Commit 526e4eaa698561eded505398babbd510df108099 inadvertently broke cross-compilation by removing `CPP="$(CPP)"` from the `guile-snarf` command line in `libguile-ssh/Makefile.am`.  The fix is to reinstate it.

Ludo'.

**Comment by civodul** [comment]
Here's the workaround I used in Guix:
https://git.savannah.gnu.org/cgit/guix.git/commit/?id=3ac1366648f933f7244c2d0b9926f7ba5d92a113

**Comment by artyom-poptsov** [comment]
Should be fixed in 0.16.0.

**Comment by Apteryks** [comment]
I guess this can be closed?

**Comment by artyom-poptsov** [comment]
Yes, indeed.
