### ISSUE TITLE
Feature request: sftp_readdir() and friends

### ISSUE THREAD

**Issue by vijaymarupudi** [artyom-poptsov/guile-ssh#33]
Thank you very much for this wonderful library!

It would be nice to see an implementation of the `sftp_opendir()`, `sftp_readdir()`, `sftp_dir_eof()`, and `sftp_closedir()` APIs, I am using the remote `find` command for now, but using the sftp way would be more performant and less error prone in my opinion.

**Comment by artyom-poptsov** [comment]
Hello.

I'm glad that the library turned out to be useful for you.

I started my work on implementing SFTP directory API in Guile-SSH on `wip-sftp-dir-type` branch.

**Comment by vijaymarupudi** [comment]
This is great news, thank you very much! Looking forward to it.

**Comment by artyom-poptsov** [comment]
I've released Guile-SSH 0.16.0 with the SFTP directory API:
https://lists.gnu.org/archive/html/guile-user/2022-09/msg00036.html

**Comment by vijaymarupudi** [comment]
Thank you very much! Looking forward to integrating it into my scripts!
