### ISSUE TITLE
Documentation for open-remote-pipe* is misleading

### ISSUE THREAD

**Issue by graywolf** [artyom-poptsov/guile-ssh#39]
The documentation claims

```
 -- Scheme Procedure: open-remote-pipe* session mode prog [args...]
     Execute PROG on the remote host with the given ARGS using a SESSION
     with a pipe to it.  Returns newly created channel port with the
     specified MODE.
```

However what is actually executed is the equivalent of `(string-append prog " " (string-join args " "))`.  That is quite surprising, given the signature of the procedure, so I believe it should be documented.

Working around it (and getting actual equivalent of `open-pipe*`) is not hard, but one has to know it is necessary and I find that somewhat hard to figure out from the current documentation.

**Comment by artyom-poptsov** [comment]
Hello!

Yes, currently `open-remote-pipe*` literally does this:
```
(open-remote-pipe session (string-join (cons prog args)) mode)
```

It's not clear for me what do you expect from the procedure.  Could you please share your workaround?  Maybe that way I can better understand how to fix the documentation (or the procedure itself, for that matter.)

Thanks,
-avp

**Comment by artyom-poptsov** [comment]
Hello!

I pushed changes that address this issue as 7a6c86fb4597abd03f96f32ca1fc07a16e6831b7

Please check if it works for you.

Thanks,
-avp
