### ISSUE TITLE
Failed to read private key

### ISSUE THREAD

**Issue by htgoebel** [artyom-poptsov/guile-ssh#5]
guile-ssh 0.11.2
When I try using `guix copy`, this fails with "Failed to read private key". I'm posting the issue here since I assume guix does not implement the key-handling itself but leaved this to guile-ssh completely.
```
$ guix copy --from=my-host guix
guix copy: error: SSH authentication failed for 'my-host': Failed to read private key: /home/me/.ssh/id_rsa-guix
```
Of course the key exists and has `-rw-------` permissions, also the pub-key exists and has `-rw-r--r--`.

I have several different keys with different algorithms. I tried with and without ssh-agent.

**Comment by artyom-poptsov** [comment]
Hello Hartmut Goebel,

could you please try to execute this program with different private keys and send me a log:
``` scheme
#!guile \
-e main -s
!#

(use-modules (ssh key)
             (ssh log))

(define (main args)
  (set-log-verbosity! 'functions)
  (let ((k (private-key-from-file (cadr args))))
    (display (get-key-type k))
    (newline)))
```

Usage example:
```
$ ./read-key.scm ~/.ssh/your_private_key
```

Thanks!

-- Artyom

**Comment by htgoebel** [comment]
Here is the output (log-time-stamps shortened):
```
;;; [2018/03/08] ssh_pki_import_privkey_base64: Trying to decode privkey passphrase=false
;;; [2018/03/08] pki_private_key_from_base64: Parsing private key
;;; [2018/03/08] private-key-from-file: [GSSH ERROR] Unable to import a key from the file: "/home/htgoebel/.ssh/id_dsa"
Backtrace:
           4 (apply-smob/1 #<catch-closure 2159a40>)
In ice-9/boot-9.scm:
    713:2  3 (call-with-prompt ("prompt") #<procedure 2161420 at ic…> …)
In ice-9/eval.scm:
    619:8  2 (_ #(#(#<directory (guile-user) 21fd140>)))
In /tmp/test.scm:
    10:11  1 (main _)
In unknown file:
           0 (private-key-from-file "/home/htgoebel/.ssh/id_dsa")

ERROR: In procedure private-key-from-file:
ERROR: Throw to key `guile-ssh-error' with args `("private-key-from-file" "Unable to import a key from the file" "/home/htgoebel/.ssh/id_dsa" #f)'.
```
Of course I verified the file exists :-) I also tried different key-types and different file-names

**Comment by artyom-poptsov** [comment]
Thanks!

> Of course I verified the file exists :-) I also tried different key-types and different file-names

Sure, I see that the key exists from the logs; yet for some reason Guile-SSH fails to parse it.   I thought logs would provide some clues.  Hmm...

Are there any errors from OpenSSH when the same `d_dsa` used with plain `ssh`?

Could you please send me the output of this program?
``` scheme
#!guile -s
!#

(use-modules (ssh version))

(format #t "libssh version: ~a~%" (get-libssh-version))
(format #t "crypto library: ~a~%" (get-crypto-library))
```

-- Artyom

**Comment by Hex4dec** [comment]
This issue occurs because of password-protected private keys. Should this be reopened or should a new issue be created?
