### ISSUE TITLE
How to execute/evaluate on a remote repl with 

### ISSUE THREAD

**Issue by bentxt** [artyom-poptsov/guile-ssh#6]
Hi,
I apologize in advance because I think my question is not limited 'guile-ssh', but some help would be greatly appreciated anyway.

Here is what I'd like to do:
- start a repl on a remote machine
- on different machine, execute a guile script which connects to the remote machine via ssh, evaluates an expression and returns a (stringified ?) result. Something like

 pseudo code 
`(define remote-sum (guile-ssh_net-eval  remote.superserver.com '(+ 8 3)))`

Do you think, this is possible, without using (the much more complicated) guile-rpc mechanism?

Thanks again for answering ...
Ben

**Comment by artyom-poptsov** [comment]
Hello Ben,

I'd recommend you to read the section `(guile-ssh) Distributed Forms` from the Info documentation shipped with Guile-SSH.  But short answer is -- yes, it is possible.  Consider this example:

``` scheme
#!guile \
-e main -s
!#

(use-modules (ice-9 rdelim)             ; write-line
             (ssh session)              ; make-session
             (ssh auth)                 ; userauth-agent!
             (ssh dist node)) ; make-node, with-ssh

;; Entry point.
(define (main args)
  ;; make a Guile-SSH session
  (let ((s (make-session #:user "avp"
                         #:host "localhost")))
    (connect! s)                        ; connect to a remote machine
    (userauth-agent! s)                 ; authenticate using SSH agent
    (let* ((n          (make-node s))   ; make a distributed computing node
           (remote-sum (with-ssh n (+ 8 3)))) ; evaluate (+ 8 3) on a RREPL
      (write-line remote-sum))))              ; print the results

```

This program starts a RREPL (Remote REPL) on the default Guile port (37146), evaluates some scheme code on the remote side and prints the results.

Hope this helps,

Artyom.
