### ISSUE TITLE
libssh_threads.so no longer exists

### ISSUE THREAD

**Issue by lantw44** [artyom-poptsov/guile-ssh#9]
It seems that `libssh_threads.so` was removed in libssh 0.8.0:
```
  CCLD     libguile-ssh.la 
/usr/bin/ld: cannot find -lssh_threads
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:490: libguile-ssh.la] Error 1
```
On Fedora, the packager of libssh workaround the removal problem by providing a `libssh_threads.so.4` symlink which points to `libssh.so.4`.

On Arch Linux, there is no such symlink and the old binaries don't run.

This problem was reported by an Arch Linux user on AUR: https://aur.archlinux.org/packages/guile-ssh/.

**Comment by jonsger** [comment]
On openSUSE we ran also into this issue. I created a [little patch](https://build.opensuse.org/package/view_file/devel:languages:misc/guile-ssh/0001-libguile-ssh-Remove-ssh_threads-from-LDFLAGS.patch?expand=1) removing `-lssh-threads` as the required symbols are now provided by `libssh.so`.

**Comment by artyom-poptsov** [comment]
Hello,

thanks for reporting that issue!  I committed a patch in 01cafef0dd87b6afda41942070e73b55b45a5ed2 that uses a more generic approach that allows to build the library with libssh 0.8 as well as with older versions.

Could you please check if the patch works for you too?

-- Artyom

**Comment by jonsger** [comment]
It works fine for openSUSE. Thanks Artyom!

**Comment by lantw44** [comment]
Thanks, it works on Arch Linux, too. By the way, do you think it is better to use `_LIBS` variables set by `PKG_CHECK_MODULES`? It won't simplify the code, but it can probably make it work in more environments.

**Comment by artyom-poptsov** [comment]
Okay, @lantw44 -- I'll look into it.  Probably you're right.

I think that this issue can be closed.  Do you agree?

**Comment by lantw44** [comment]
Yes, it can be closed.

**Comment by JohnAZoidberg** [comment]
A new release would be appreciated.
